name: Validate for PR
on: push
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Install dependencies
        run: make deps
        env:
          GO111MODULE: on
          GOPATH: /home/runner/go
      - name: Linting
        run: make lint
        env:
          GO111MODULE: on
          GOPATH: /home/runner/go
      - name: Test
        run: make test
        env:
          GO111MODULE: on
          GOPATH: /home/runner/go
      - name: Build
        run: make build
        env:
          GO111MODULE: on
          GOPATH: /home/runner/go
      - name: Acceptance Test
        run: make acceptance-test
        env:
          GO111MODULE: on
          GOPATH: /home/runner/go
      
